TF_F_POSTINFO
TBS_CRM_DUSR1

partition by range (PARTITION_ID)
(
   partition PAR_TF_F_POSTINFO_0   values less than (100)   tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_1   values less than (200)   tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_2   values less than (300)   tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_3   values less than (400)   tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_4   values less than (500)   tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_5   values less than (600)   tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_6   values less than (700)   tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_7   values less than (800)   tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_8   values less than (900)   tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_9   values less than (1000)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_10  values less than (1100)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_11  values less than (1200)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_12  values less than (1300)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_13  values less than (1400)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_14  values less than (1500)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_15  values less than (1600)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_16  values less than (1700)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_17  values less than (1800)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_18  values less than (1900)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_19  values less than (2000)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_20  values less than (2100)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_21  values less than (2200)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_22  values less than (2300)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_23  values less than (2400)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_24  values less than (2500)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_25  values less than (2600)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_26  values less than (2700)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_27  values less than (2800)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_28  values less than (2900)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_29  values less than (3000)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_30  values less than (3100)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_31  values less than (3200)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_32  values less than (3300)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_33  values less than (3400)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_34  values less than (3500)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_35  values less than (3600)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_36  values less than (3700)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_37  values less than (3800)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_38  values less than (3900)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_39  values less than (4000)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_40  values less than (4100)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_41  values less than (4200)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_42  values less than (4300)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_43  values less than (4400)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_44  values less than (4500)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_45  values less than (4600)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_46  values less than (4700)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_47  values less than (4800)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_48  values less than (4900)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_49  values less than (5000)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_50  values less than (5100)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_51  values less than (5200)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_52  values less than (5300)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_53  values less than (5400)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_54  values less than (5500)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_55  values less than (5600)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_56  values less than (5700)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_57  values less than (5800)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_58  values less than (5900)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_59  values less than (6000)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_60  values less than (6100)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_61  values less than (6200)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_62  values less than (6300)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_63  values less than (6400)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_64  values less than (6500)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_65  values less than (6600)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_66  values less than (6700)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_67  values less than (6800)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_68  values less than (6900)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_69  values less than (7000)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_70  values less than (7100)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_71  values less than (7200)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_72  values less than (7300)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_73  values less than (7400)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_74  values less than (7500)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_75  values less than (7600)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_76  values less than (7700)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_77  values less than (7800)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_78  values less than (7900)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_79  values less than (8000)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_80  values less than (8100)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_81  values less than (8200)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_82  values less than (8300)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_83  values less than (8400)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_84  values less than (8500)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_85  values less than (8600)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_86  values less than (8700)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_87  values less than (8800)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_88  values less than (8900)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_89  values less than (9000)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_90  values less than (9100)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_91  values less than (9200)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_92  values less than (9300)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_93  values less than (9400)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_94  values less than (9500)	 tablespace TBS_CRM_DUSR5   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_95  values less than (9600)	 tablespace TBS_CRM_DUSR1   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_96  values less than (9700)	 tablespace TBS_CRM_DUSR2   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_97  values less than (9800)	 tablespace TBS_CRM_DUSR3   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_98  values less than (9900)	 tablespace TBS_CRM_DUSR4   pctfree 20  initrans 10,  
   partition PAR_TF_F_POSTINFO_99 	values less than (MAXVALUE)	tablespace TBS_CRM_DUSR5 pctfree 20  initrans 10
);



pctfree 10 initrans 20 tablespace TBS_CRM_IUSR1
local
(
   partition PAR_TF_F_POSTINFO_0   tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_1   tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_2   tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_3   tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_4   tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_5   tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_6   tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_7   tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_8   tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_9   tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_10  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_11  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_12  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_13  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_14  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_15  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_16  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_17  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_18  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_19  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_20  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_21  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_22  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_23  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_24  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_25  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_26  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_27  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_28  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_29  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_30  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_31  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_32  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_33  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_34  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_35  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_36  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_37  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_38  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_39  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_40  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_41  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_42  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_43  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_44  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_45  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_46  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_47  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_48  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_49  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_50  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_51  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_52  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_53  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_54  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_55  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_56  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_57  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_58  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_59  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_60  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_61  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_62  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_63  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_64  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_65  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_66  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_67  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_68  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_69  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_70  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_71  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_72  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_73  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_74  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_75  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_76  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_77  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_78  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_79  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_80  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_81  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_82  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_83  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_84  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_85  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_86  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_87  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_88  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_89  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_90  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_91  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_92  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_93  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_94  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_95  tablespace TBS_CRM_IUSR1 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_96  tablespace TBS_CRM_IUSR2 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_97  tablespace TBS_CRM_IUSR3 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_98  tablespace TBS_CRM_IUSR4 pctfree 10  initrans 20,  
   partition PAR_TF_F_POSTINFO_99  tablespace TBS_CRM_IUSR5 pctfree 10  initrans 20
);

local
(
   partition PAR_TS_B_GPRSRATEINFO_1    tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_2    tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_3    tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_4    tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_5    tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_6    tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_7    tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_8    tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_9    tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_10   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_11   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_12   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_13   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_14   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_15   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_16   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_17   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_18   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_19   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_20   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_21   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_22   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_23   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_24   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_25   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_26   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_27   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_28   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_29   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_30   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_31   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_32   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_33   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_34   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_35   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_36   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_37   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_38   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_39   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_40   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_41   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_42   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_43   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_44   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_45   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_46   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_47   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_48   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_49   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_50   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_51   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_52   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_53   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_54   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_55   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_56   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_57   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_58   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_59   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_60   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_61   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_62   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_63   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_64   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_65   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_66   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_67   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_68   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_69   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_70   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_71   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_72   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_73   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_74   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_75   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_76   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_77   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_78   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_79   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_80   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_81   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_82   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_83   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_84   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_85   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_86   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_87   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_88   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_89   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_90   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_91   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_92   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_93   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_94   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_95   tablespace TBS_BIL_IACT05 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_96   tablespace TBS_BIL_IACT01 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_97   tablespace TBS_BIL_IACT02 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_98   tablespace TBS_BIL_IACT03 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_99   tablespace TBS_BIL_IACT04 pctfree 10  initrans 20,  
   partition PAR_TS_B_GPRSRATEINFO_100  tablespace TBS_BIL_IACT05 pctfree 10  initrans 20
);


