alter table TI_C_SUBSCRIBE
   add constraint PK_TI_C_SUBSCRIBE primary key (SUBSCRIBE_ID, DEAL_SEQ, USER_PARTITION, EXEC_MONTH)
   using index
  TABLESPACE tbs_cen_iuif
  PCTFREE    10
  INITRANS   10
  MAXTRANS   255
LOCAL (  
  PARTITION U01
    INITRANS   10
    MAXTRANS   255
  ( SUBPARTITION U01_M01      TABLESPACE TBS_CEN_IUIF,
    SUBPARTITION U01_M02      TABLESPACE TBS_CEN_IUIF,
    SUBPARTITION U01_M03      TABLESPACE TBS_CEN_IUIF,
    SUBPARTITION U01_M04      TABLESPACE TBS_CEN_IUIF,
    SUBPARTITION U01_M05      TABLESPACE TBS_CEN_IUIF,
    SUBPARTITION U01_M06      TABLESPACE TBS_CEN_IUIF,
    SUBPARTITION U01_M07      TABLESPACE TBS_CEN_IUIF,
    SUBPARTITION U01_M08      TABLESPACE TBS_CEN_IUIF,
    SUBPARTITION U01_M09      TABLESPACE TBS_CEN_IUIF,
    SUBPARTITION U01_M10      TABLESPACE TBS_CEN_IUIF,
    SUBPARTITION U01_M11      TABLESPACE TBS_CEN_IUIF,
    SUBPARTITION U01_M12      TABLESPACE TBS_CEN_IUIF ),  
  PARTITION U02
    INITRANS   10
    MAXTRANS   255
  ( SUBPARTITION U02_M01      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U02_M02      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U02_M03      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U02_M04      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U02_M05      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U02_M06      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U02_M07      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U02_M08      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U02_M09      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U02_M10      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U02_M11      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U02_M12      TABLESPACE TBS_CEN_IUIF ), 
  PARTITION U03
    INITRANS   10
    MAXTRANS   255
  ( SUBPARTITION U03_M01      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U03_M02      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U03_M03      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U03_M04      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U03_M05      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U03_M06      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U03_M07      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U03_M08      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U03_M09      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U03_M10      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U03_M11      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U03_M12      TABLESPACE TBS_CEN_IUIF ),  
  PARTITION U04
    INITRANS   10
    MAXTRANS   255
  ( SUBPARTITION U04_M01      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U04_M02      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U04_M03      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U04_M04      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U04_M05      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U04_M06      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U04_M07      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U04_M08      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U04_M09      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U04_M10      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U04_M11      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U04_M12      TABLESPACE TBS_CEN_IUIF ),  
  PARTITION U05
    INITRANS   10
    MAXTRANS   255
  ( SUBPARTITION U05_M01      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U05_M02      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U05_M03      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U05_M04      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U05_M05      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U05_M06      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U05_M07      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U05_M08      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U05_M09      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U05_M10      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U05_M11      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U05_M12      TABLESPACE TBS_CEN_IUIF ),  
  PARTITION U06
    INITRANS   10
    MAXTRANS   255
  ( SUBPARTITION U06_M01      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U06_M02      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U06_M03      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U06_M04      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U06_M05      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U06_M06      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U06_M07      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U06_M08      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U06_M09      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U06_M10      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U06_M11      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U06_M12      TABLESPACE TBS_CEN_IUIF ),  
  PARTITION U07
    INITRANS   10
    MAXTRANS   255
  ( SUBPARTITION U07_M01      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U07_M02      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U07_M03      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U07_M04      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U07_M05      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U07_M06      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U07_M07      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U07_M08      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U07_M09      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U07_M10      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U07_M11      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U07_M12      TABLESPACE TBS_CEN_IUIF ),  
  PARTITION U08
    INITRANS   10
    MAXTRANS   255
  ( SUBPARTITION U08_M01      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U08_M02      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U08_M03      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U08_M04      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U08_M05      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U08_M06      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U08_M07      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U08_M08      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U08_M09      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U08_M10      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U08_M11      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U08_M12      TABLESPACE TBS_CEN_IUIF ),  
  PARTITION U09
    INITRANS   10
    MAXTRANS   255
  ( SUBPARTITION U09_M01      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U09_M02      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U09_M03      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U09_M04      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U09_M05      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U09_M06      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U09_M07      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U09_M08      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U09_M09      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U09_M10      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U09_M11      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U09_M12      TABLESPACE TBS_CEN_IUIF ),  
  PARTITION U10
    INITRANS   10
    MAXTRANS   255
  ( SUBPARTITION U10_M01      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U10_M02      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U10_M03      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U10_M04      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U10_M05      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U10_M06      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U10_M07      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U10_M08      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U10_M09      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U10_M10      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U10_M11      TABLESPACE TBS_CEN_IUIF,  
    SUBPARTITION U10_M12      TABLESPACE TBS_CEN_IUIF )
);