EXEC DBMS_SQLTUNE.CREATE_STGTAB_SQLSET('SST_CRM1016EXECI1','UBAK','TBS_CRM_DEF');
EXEC DBMS_SQLTUNE.PACK_STGTAB_SQLSET( SQLSET_NAME => 'SQLSET_CRM1016_EXECi1',SQLSET_OWNER => 'UBAK',STAGING_TABLE_NAME => 'SST_CRM1016EXECI1', STAGING_SCHEMA_OWNER => 'UBAK');
exit;

EXEC DBMS_SQLTUNE.CREATE_STGTAB_SQLSET('SST_CRM1016EXECI2','UBAK','TBS_CRM_DEF');
EXEC DBMS_SQLTUNE.PACK_STGTAB_SQLSET( SQLSET_NAME => 'SQLSET_CRM1016_EXECi2',SQLSET_OWNER => 'UBAK',STAGING_TABLE_NAME => 'SST_CRM1016EXECI2', STAGING_SCHEMA_OWNER => 'UBAK');
exit;

nohup sqlplus ubak/ubakabc@10.238.160.84/ngcrm @spa_packi1.sql > 1.out &
nohup sqlplus ubak/ubakabc@10.238.160.86/ngcrm @spa_packi2.sql > 2.out &

EXEC DBMS_SQLTUNE.CREATE_STGTAB_SQLSET('SST_CUS0121DANGI1','UBAK','TBS_CUS_DEF');
EXEC DBMS_SQLTUNE.PACK_STGTAB_SQLSET( SQLSET_NAME => 'SQLSET_CUS0121_EXECi1',SQLSET_OWNER => 'UBAK',STAGING_TABLE_NAME => 'SST_CUS0121DANGI1', STAGING_SCHEMA_OWNER => 'UBAK');
exit;

EXEC DBMS_SQLTUNE.CREATE_STGTAB_SQLSET('SST_CUS0121DANGTI1','UBAK','TBS_CUS_DEF');
EXEC DBMS_SQLTUNE.PACK_STGTAB_SQLSET( SQLSET_NAME => 'SQLSET_CUS0121_EXECi1',SQLSET_OWNER => 'UBAK',STAGING_TABLE_NAME => 'SST_CUS0121DANGTI1', STAGING_SCHEMA_OWNER => 'UBAK');

